// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace logjoint.graphics.test
{
	public partial class GraphicsTestMainWindow : NSWindow
	{
		public GraphicsTestMainWindow (IntPtr handle) : base (handle)
		{
		}
	}
}
