// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Xml;
using LogJoint;

namespace LogViewerTests
{
	[TestClass()]
	public class FieldsMappingTest: IMessagesBuilderCallback
	{
		XmlElement CreateConfigNode(string config)
		{
			XmlDocument doc = new XmlDocument();
			doc.LoadXml(config);
			return doc.DocumentElement;
		}

		[TestMethod()]
		public void MakeLineTest()
		{
			FieldsProcessor target = new FieldsProcessor(CreateConfigNode(@"
<config>
	<field name='Time'>TO_DATETIME(TimeGenerated, DEFAULT_DATETIME_FORMAT())</field>
	<field name='My Field'>TimeGenerated + Field1</field>
	<field name='Body' code-type='function'>
		StringBuilder ret = new StringBuilder();
		for (int i = 1; i &lt; INPUT_FIELDS_COUNT(); ++i)
			ret.Append(INPUT_FIELD_VALUE(i));
		return ret.ToString();
	</field>
</config>
			"), false);

			target.Reset();
			target.SetInputField(0, "TimeGenerated", "2009-02-03 12:34:56");
			target.SetInputField(1, null, "123");

			MessageBase msg1 = target.MakeMessage(this);
		}


		#region ILineBuilderCallback Members

		public IThread GetThread(string id)
		{
			return (new LogJoint.Threads()).RegisterThread(id, null);
		}

		public long CurrentPosition 
		{
			get { return 0; }
		}

		#endregion
	}

}
