// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.IO;
using LogJoint.StreamSearch;

namespace LogViewerTests
{
	[TestClass()]
	public class TrieNodeTest
	{
		void DoTest(TrieNode n, string streamStr, long initialPos, long? expected)
		{
			Stream s = new MemoryStream(Encoding.UTF8.GetBytes(streamStr));
			s.Position = initialPos;
			Assert.AreEqual<long?>(expected, n.Find(s));
		}

		/// <summary>
		///A test for Find (Stream)
		///</summary>
		[DeploymentItem("LogJoint.exe")]
		[TestMethod()]
		public void FindTest()
		{
			TrieNode n = new TrieNode();

			DoTest(n, "", 0, null);
			DoTest(n, "qwe", 0, null);
			DoTest(n, "qwe", 1, null);
			DoTest(n, "йцу", 0, null);
			DoTest(n, "йцу", 1, null);
			DoTest(n, "йцу", 2, null);

			n.Add(Encoding.UTF8.GetBytes("bar"), 0);
			n.Add(Encoding.UTF8.GetBytes("ba"), 0);
			DoTest(n, "bar", 0, 0);
			DoTest(n, "bba", 0, 1);
			DoTest(n, "bbaarr", 0, 1);
			DoTest(n, "йцbaук", 1, 4);
			DoTest(n, "йцbукar", 1, null);
		}

	}


}
